# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Common Workflow Language
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Common Workflow Language (CWL) is an open standard for describing 
  analysis workflows and tools in a way that makes them portable and scalable 
  across a variety of software and hardware environments, from workstations 
  to cluster, cloud, and high performance computing (HPC) environments. 
  CWL is designed to meet the needs of data-intensive science, such as 
  Bioinformatics, Medical Imaging, Astronomy, High Energy Physics, and 
  Machine Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - scratch
  - "*.sh"
  - README.md

collections_dir: collections
collections: 
  home-sections: 
    output: false